apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Chart.Name }}-app-warning
  namespace: {{ index .Values.elastalert.namespace }}
  labels:
    app: {{ $.Chart.Name }}
data:
  app-warning: |-
    ---
    name: Aplication warning
    type: frequency
    index: vertcoin-*
    num_events: 1
    timeframe:
        minutes: 5
    include: ["@timestamp", "kubernetes.labels.app", "level", "message"]
    filter:
    - query:
        query_string:
          query: 'level: "warning"'
    alert:
    - "slack"
    alert_subject: "{0} caught {1} on stage"
    alert_subject_args:
    - kubernetes.labels.app
    - level
    alert_text: "{0}"
    alert_text_args:
    - message
    alert_text_type: alert_text_only
    slack_webhook_url: "https://hooks.slack.com/services/--------"
    slack_username_override: "elastalert"
    slack_msg_color: danger
