apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Chart.Name }}-config
  labels:
    app: {{ $.Chart.Name }}
data:
  elastalert_config: |-
    ---
    rules_folder: /opt/rules
    scan_subdirectories: false
    run_every:
      minutes: {{ .Values.runIntervalMins }}
    buffer_time:
      minutes: {{ .Values.bufferTimeMins }}
    es_host: {{ .Values.elasticsearch.host }}
    es_port: {{ .Values.elasticsearch.port }}
    writeback_index: {{ .Values.writebackIndex }}
    use_ssl: {{ .Values.elasticsearch.useSsl }}
    alert_time_limit:
      days: 2