apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Chart.Name }}
  namespace: logging
  labels:
    app: {{ $.Chart.Name }}
data:
  action_file.yml: |-
    ---
    # Remember, leave a key empty if there is no value.  None will be a string,
    # not a Python "NoneType"
    #
    # Also remember that all examples have 'disable_action' set to True.  If you
    # want to use this action as a template, be sure to set this to False after
    # copying it.
    actions:
      1:
        action: delete_indices
        description: "delete vertcoin indices"
        options:
          timeout_override:
          continue_if_exception: False
          disable_action: False
          ignore_empty_list: True
        filters:
        - filtertype: age
          source: name
          direction: older
          timestring: '{{ .Values.curator.vertcoin.timestring }}'
          unit: {{ .Values.curator.vertcoin.unit }}
          unit_count: {{ .Values.curator.vertcoin.unit_count }}
          field:
          stats_result:
          epoch:
          exclude: False
        - filtertype: pattern
          kind: prefix
          value: vertcoin-
      2:
        action: delete_indices
        description: "delete bicoin indices"
        options:
          timeout_override:
          continue_if_exception: False
          disable_action: False
          ignore_empty_list: True
        filters:
        - filtertype: age
          source: name
          direction: older
          timestring: '{{ .Values.curator.bitcoin.timestring }}'
          unit: {{ .Values.curator.bitcoin.unit }}
          unit_count: {{ .Values.curator.bitcoin.unit_count }}
          field:
          stats_result:
          epoch:
          exclude: False
        - filtertype: pattern
          kind: prefix
          value: bitcoin-
  config.yml: |-
    ---
    # Remember, leave a key empty if there is no value.  None will be a string,
    # not a Python "NoneType"
    client:
      hosts:
        - {{ .Values.service.elastichost }}
      port: {{ .Values.service.elasticport }}
      url_prefix:
      use_ssl: False
      certificate:
      client_cert:
      client_key:
      ssl_no_validate: False
      http_auth:
      timeout: 30
      master_only: False
    logging:
      loglevel: INFO
      logfile:
      logformat: default
      blacklist: ['elasticsearch', 'urllib3']
