apiVersion: v1
kind: Service
metadata:
  name: main_app_worker
  namespace: project
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 12345
    targetPort: 12345    
  selector:
    app: worker
status:
  loadBalancer: {}