apiVersion: v1
kind: Service
metadata:
  name: main_app-node
  namespace: project
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
    nodePort: 30900
  selector:
    app: main_app
status:
  loadBalancer: {}