apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: main_app-parity-classic.yaml
spec:
 accessModes:
  - ReadWriteMany
 storageClassName: glusterfs-storage  
 resources:
   requests:
     storage: 5Gi