apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}-discovery
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: {{ template "name" . }}
    role: master
spec:
  selector:
    component: {{ template "name" . }}
    role: master
  ports:
  - name: transport
    port: 9300
    protocol: TCP
