apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Chart.Name }}-logstash
  namespace: {{ index .Values "logstash" "namespace" }}
data:
  logstash.conf: |-
    input {
      http {
        port => 5045
        codec => "json"
      }
    }