apiVersion: v1
kind: Service
metadata:
  name: {{ $.Chart.Name }}
  namespace: {{ index .Values "logstash" "namespace" }}
  labels:
    app: {{ $.Chart.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ $.Chart.Name }}
  ports:
{{ index .Values "logstash" "serviceports" | toYaml | indent 2 }}